"""
常用球员中英文名映射（五大联赛）
注意：Python dict 会取最后一个重复 key 的值，请勿添加重复 key
"""
PLAYERS_CN = {
    # ===== 英超 =====
    # 曼城
    "Erling Haaland": "哈兰德", "Kevin De Bruyne": "德布劳内",
    "Phil Foden": "福登", "Rodri": "罗德里", "Jack Grealish": "格拉利什",
    "Ruben Dias": "鲁本·迪亚斯", "Bernardo Silva": "B席",
    "Jeremy Doku": "多库", "Josko Gvardiol": "格瓦迪奥尔",
    "Omar Marmoush": "马尔穆什", "Mateo Kovacic": "科瓦西奇",
    "John Stones": "斯通斯", "Kyle Walker": "沃克",
    "Ederson": "埃德森", "Stefan Ortega": "奥尔特加",
    "Manuel Akanji": "阿坎吉", "Nathan Ake": "阿克",
    # 阿森纳
    "Bukayo Saka": "萨卡", "Martin Odegaard": "厄德高",
    "Gabriel Jesus": "热苏斯", "Declan Rice": "赖斯",
    "William Saliba": "萨利巴", "Gabriel Magalhaes": "加布里埃尔",
    "Ben White": "本·怀特", "Leandro Trossard": "特罗萨德",
    "Kai Havertz": "哈弗茨", "Martinelli": "马丁内利",
    "Gabriel Martinelli": "马丁内利", "Thomas Partey": "托马斯",
    "Mikel Merino": "梅里诺", "Jurrien Timber": "廷贝尔",
    "David Raya": "拉亚", "Riccardo Calafiori": "卡拉菲奥里",
    "Raheem Sterling": "斯特林", "Ethan Nwaneri": "恩瓦内里",
    "Myles Lewis-Skelly": "刘易斯-斯凯利",
    # 利物浦
    "Mohamed Salah": "萨拉赫", "Mo Salah": "萨拉赫",
    "Virgil van Dijk": "范迪克", "Van Dijk": "范迪克",
    "Trent Alexander-Arnold": "阿诺德", "Trent": "阿诺德",
    "Alisson Becker": "阿利松", "Alisson": "阿利松",
    "Darwin Nunez": "努涅斯", "Luis Diaz": "路易斯·迪亚斯",
    "Cody Gakpo": "加克波", "Dominik Szoboszlai": "索博斯洛伊",
    "Alexis Mac Allister": "麦卡利斯特", "Ryan Gravenberch": "赫拉芬贝赫",
    "Ibrahima Konate": "科纳特", "Andy Robertson": "罗伯逊",
    "Joe Gomez": "乔·戈麦斯", "Diogo Jota": "若塔",
    "Jota": "若塔", "Federico Chiesa": "基耶萨",
    # 曼联
    "Bruno Fernandes": "B费", "Marcus Rashford": "拉什福德",
    "Rasmus Hojlund": "霍伊伦", "Alejandro Garnacho": "加纳乔",
    "Garnacho": "加纳乔", "Kobbie Mainoo": "梅努",
    "Andre Onana": "奥纳纳", "Lisandro Martinez": "利马",
    "Licha": "利马", "Mason Mount": "芒特",
    "Casemiro": "卡塞米罗", "Amad Diallo": "阿马德",
    "Amad": "阿马德", "Joshua Zirkzee": "齐尔克泽",
    "Leny Yoro": "约罗", "Manuel Ugarte": "乌加特",
    "Harry Maguire": "马奎尔", "Luke Shaw": "卢克·肖",
    "Raphael Varane": "瓦拉内",
    # 切尔西
    "Cole Palmer": "帕尔默", "Palmer": "帕尔默",
    "Nicolas Jackson": "雅克松", "Moises Caicedo": "凯塞多",
    "Enzo Fernandez": "恩佐", "Enzo": "恩佐",
    "Reece James": "里斯·詹姆斯", "Levi Colwill": "科尔威尔",
    "Malo Gusto": "古斯托", "Romeo Lavia": "拉维亚",
    "Christopher Nkunku": "恩昆库", "Nkunku": "恩昆库",
    "Mykhailo Mudryk": "穆德里克", "Mudryk": "穆德里克",
    "Conor Gallagher": "加拉格尔", "Gallagher": "加拉格尔",
    "Axel Disasi": "迪萨西", "Benoit Badiashile": "巴迪亚西勒",
    "Marc Cucurella": "库库雷利亚", "Wesley Fofana": "福法纳",
    "Carney Chukwuemeka": "楚克乌梅卡",
    "Pedro Neto": "佩德罗·内托", "Neto": "内托",
    # 热刺
    "Son Heung-min": "孙兴慜", "Sonny": "孙兴慜",
    "James Maddison": "麦迪逊", "Maddison": "麦迪逊",
    "Cristian Romero": "C·罗梅罗", "Romero": "罗梅罗",
    "Guglielmo Vicario": "维卡里奥", "Destiny Udogie": "乌多吉",
    "Pedro Porro": "波罗", "Micky van de Ven": "范德芬",
    "Brennan Johnson": "布伦南·约翰逊", "Johnson": "约翰逊",
    "Dejan Kulusevski": "库卢塞夫斯基", "Richarlison": "理查利森",
    "Timo Werner": "维尔纳", "Pape Matar Sarr": "萨尔",
    "Yves Bissouma": "比苏马", "Rodrigo Bentancur": "本坦库尔",
    # 纽卡
    "Alexander Isak": "伊萨克", "Isak": "伊萨克",
    "Bruno Guimaraes": "吉马良斯", "Joelinton": "乔林顿",
    "Anthony Gordon": "安东尼·戈登", "Gordon": "戈登",
    "Sandro Tonali": "托纳利", "Kieran Trippier": "特里皮尔",
    "Trippier": "特里皮尔", "Callum Wilson": "威尔逊",
    "Nick Pope": "波普", "Sven Botman": "博特曼",
    "Elliot Anderson": "安德森",
    # 维拉
    "Ollie Watkins": "沃特金斯", "Watkins": "沃特金斯",
    "John McGinn": "麦金", "Youri Tielemans": "蒂勒曼斯",
    "Pau Torres": "保·托雷斯", "Jhon Duran": "杜兰",
    "Leon Bailey": "贝利", "Emiliano Martinez": "大马丁",
    "Emi Martinez": "大马丁", "Tyrone Mings": "明斯",
    "Ezri Konsa": "孔萨", "Morgan Rogers": "罗杰斯",
    "Boubacar Kamara": "卡马拉",

    # ===== 西甲 =====
    # 皇马
    "Kylian Mbappe": "姆巴佩", "Mbappe": "姆巴佩",
    "Vinicius Junior": "维尼修斯", "Vini Jr": "维尼修斯",
    "Jude Bellingham": "贝林厄姆", "Bellingham": "贝林厄姆",
    "Rodrygo": "罗德里戈", "Federico Valverde": "巴尔韦德",
    "Eduardo Camavinga": "卡马文加", "Aurelien Tchouameni": "琼阿梅尼",
    "Daniel Carvajal": "卡瓦哈尔", "Antonio Rudiger": "吕迪格",
    "David Alaba": "阿拉巴", "Eder Militao": "米利唐",
    "Thibaut Courtois": "库尔图瓦", "Luka Modric": "莫德里奇",
    "Modric": "莫德里奇", "Toni Kroos": "克罗斯",
    "Brahim Diaz": "迪亚斯", "Arda Guler": "居莱尔",
    "Endrick": "恩德里克",
    # 巴萨
    "Lamine Yamal": "亚马尔", "Yamal": "亚马尔",
    "Robert Lewandowski": "莱万", "Lewandowski": "莱万",
    "Pedri": "佩德里", "Gavi": "加维",
    "Raphinha": "拉菲尼亚", "Fermin Lopez": "费尔明",
    "Alejandro Balde": "巴尔德", "Ronald Araujo": "阿劳霍",
    "Andreas Christensen": "克里斯滕森", "Pau Cubarsi": "库巴西",
    "Marc Casado": "卡萨多", "Dani Olmo": "奥尔莫",
    "Inigo Martinez": "伊尼戈", "Frenkie de Jong": "德容",
    "De Jong": "德容", "Ilkay Gundogan": "京多安",
    # 马竞
    "Antoine Griezmann": "格列兹曼", "Griezmann": "格列兹曼",
    "Alvaro Morata": "莫拉塔", "Morata": "莫拉塔",
    "Jan Oblak": "奥布拉克", "Koke": "科克",
    "Jose Maria Gimenez": "希门尼斯", "Rodrigo De Paul": "德保罗",
    "De Paul": "德保罗", "Pablo Barrios": "巴里奥斯",
    "Samuel Lino": "利诺", "Nahuel Molina": "莫利纳",
    "Marcos Llorente": "略伦特", "Angel Correa": "科雷亚",
    "Julian Alvarez": "阿尔瓦雷斯",

    # ===== 德甲 =====
    # 拜仁
    "Harry Kane": "凯恩", "Kane": "凯恩",
    "Jamal Musiala": "穆西亚拉", "Musiala": "穆西亚拉",
    "Manuel Neuer": "诺伊尔", "Joshua Kimmich": "基米希",
    "Kimmich": "基米希",
    "Leroy Sane": "萨内", "Sane": "萨内",
    "Serge Gnabry": "格纳布里", "Alphonso Davies": "阿方索·戴维斯",
    "Davies": "戴维斯", "Kim Min-jae": "金玟哉",
    "Dayot Upamecano": "于帕梅卡诺", "Upamecano": "于帕梅卡诺",
    "Max Eberl": "埃贝尔", "Michael Olise": "奥利斯",
    "Olise": "奥利斯", "Aleksandar Pavlovic": "帕夫洛维奇",
    "Konrad Laimer": "莱默尔", "Leon Goretzka": "戈雷茨卡",
    "Goretzka": "戈雷茨卡", "Joao Palhinha": "帕利尼亚",
    "Sacha Boey": "博伊", "Hiroki Ito": "伊藤洋辉",
    # 多特
    "Karim Adeyemi": "阿德耶米", "Adeyemi": "阿德耶米",
    "Julian Brandt": "布兰特", "Brandt": "布兰特",
    "Marco Reus": "罗伊斯", "Reus": "罗伊斯",
    "Jadon Sancho": "桑乔", "Sancho": "桑乔",
    "Emre Can": "詹", "Donyell Malen": "马伦",
    "Mats Hummels": "胡梅尔斯", "Hummels": "胡梅尔斯",
    "Niklas Sule": "聚勒", "Felix Nmecha": "恩梅查",
    "Jamie Gittens": "吉滕斯", "Youssoufa Moukoko": "穆科科",
    "Gregor Kobel": "科贝尔", "Nico Schlotterbeck": "施洛特贝克",
    "Julian Ryerson": "瑞尔森", "Ramy Bensebaini": "本塞拜尼",
    # 勒沃库森
    "Florian Wirtz": "维尔茨", "Wirtz": "维尔茨",
    "Aleix Garcia": "A·加西亚", "Granit Xhaka": "扎卡",
    "Xhaka": "扎卡", "Jeremie Frimpong": "弗林蓬",
    "Victor Boniface": "博尼费斯", "Patrik Schick": "希克",
    "Edmond Tapsoba": "塔普索巴", "Jonathan Tah": "若纳坦·塔",
    "Tah": "塔", "Exequiel Palacios": "帕拉西奥斯",
    "Lukas Hradecky": "赫拉德茨基", "Piero Hincapie": "因卡皮耶",

    # ===== 意甲 =====
    # 国米
    "Lautaro Martinez": "劳塔罗", "Lautaro": "劳塔罗",
    "Marcus Thuram": "小图拉姆", "Thuram": "图拉姆",
    "Nicolo Barella": "巴雷拉", "Hakan Calhanoglu": "恰尔汗奥卢",
    "Henrikh Mkhitaryan": "姆希塔良", "Denzel Dumfries": "邓弗里斯",
    "Alessandro Bastoni": "巴斯托尼", "Francesco Acerbi": "阿切尔比",
    "Stefan de Vrij": "德弗赖", "Yann Sommer": "索默",
    "Federico Dimarco": "迪马尔科", "Benjamin Pavard": "帕瓦尔",
    "Piotr Zielinski": "泽林斯基", "Mehdi Taremi": "塔雷米",
    "Davide Frattesi": "弗拉泰西", "Kristjan Asllani": "阿斯拉尼",
    # AC米兰
    "Rafael Leao": "莱奥", "Leao": "莱奥",
    "Theo Hernandez": "特奥", "Theo": "特奥",
    "Fikayo Tomori": "托莫里", "Mike Maignan": "迈尼昂",
    "Maignan": "迈尼昂", "Christian Pulisic": "普利西奇",
    "Pulisic": "普利西奇", "Olivier Giroud": "吉鲁",
    "Ismael Bennacer": "本纳塞尔", "Tijjani Reijnders": "赖因德斯",
    "Yacine Adli": "阿德利", "Malick Thiaw": "佳夫",
    "Davide Calabria": "卡拉布里亚", "Matteo Gabbia": "加比亚",
    "Noah Okafor": "奥卡福", "Ruben Loftus-Cheek": "奇克",
    "Samuel Chukwueze": "丘库埃泽",
    # 尤文
    "Dusan Vlahovic": "弗拉霍维奇", "Vlahovic": "弗拉霍维奇",
    "Kenan Yildiz": "伊尔迪兹", "Gleison Bremer": "布雷默",
    "Bremer": "布雷默", "Federico Gatti": "加蒂",
    "Manuel Locatelli": "洛卡特利", "Adrien Rabiot": "拉比奥",
    "Rabiot": "拉比奥", "Weston McKennie": "麦肯尼",
    "Andrea Cambiaso": "坎比亚索", "Mattia Perin": "佩林",
    "Teun Koopmeiners": "库普梅纳斯", "Douglas Luiz": "道格拉斯·路易斯",
    "Nicolas Gonzalez": "冈萨雷斯", "Michele Di Gregorio": "迪格雷戈里奥",
    "Khephren Thuram": "K·图拉姆",
    # 那不勒斯
    "Victor Osimhen": "奥斯梅恩", "Osimhen": "奥斯梅恩",
    "Khvicha Kvaratskhelia": "克瓦拉茨赫利亚", "Kvaratskhelia": "KK",
    "Lobotka": "洛博特卡", "Stanislav Lobotka": "洛博特卡",
    "Andre Zambo Anguissa": "安古伊萨", "Giovanni Di Lorenzo": "迪洛伦佐",
    "Amir Rrahmani": "拉赫马尼", "Alex Meret": "梅雷特",
    "Giacomo Raspadori": "拉斯帕多里", "Matteo Politano": "波利塔诺",

    # ===== 法甲 =====
    # PSG
    "Ousmane Dembele": "登贝莱", "Dembele": "登贝莱",
    "Randal Kolo Muani": "科洛·穆阿尼", "Kolo Muani": "穆阿尼",
    "Marquinhos": "马尔基尼奥斯", "Achraf Hakimi": "阿什拉夫",
    "Hakimi": "阿什拉夫", "Warren Zaire-Emery": "埃梅里",
    "Fabian Ruiz": "法比安·鲁伊斯", "Ruiz": "鲁伊斯",
    "Vitinha": "维蒂尼亚", "Milan Skriniar": "什克里尼亚尔",
    "Lucas Hernandez": "卢卡斯·埃尔南德斯", "Presnel Kimpembe": "金彭贝",
    "Gianluigi Donnarumma": "多纳鲁马", "Donnarumma": "多纳鲁马",
    "Goncalo Ramos": "G·拉莫斯", "Bradley Barcola": "巴尔科拉",
    "Lee Kang-in": "李刚仁", "Joao Neves": "若昂·内维斯",
    "Kang-in Lee": "李刚仁",
    # 摩纳哥
    "Wissam Ben Yedder": "本耶德尔",
    "Youssouf Fofana": "福法纳", "Fofana": "福法纳",
    "Aleksandr Golovin": "戈洛温", "Eliesse Ben Seghir": "本·塞吉尔",
    "Maghnes Akliouche": "阿克利乌什",
    "Breel Embolo": "恩博洛", "Vanderson": "范德森",
    "Thilo Kehrer": "科雷尔",
    # 里昂
    "Alexandre Lacazette": "拉卡泽特", "Lacazette": "拉卡泽特",
    "Corentin Tolisso": "托利索", "Nicolas Tagliafico": "塔利亚菲科",
    "Rayan Cherki": "切尔基", "Cherki": "切尔基",

    # ===== 沙特/其他联赛热门 =====
    "Neymar": "内马尔", "Neymar Jr": "内马尔",
    "Cristiano Ronaldo": "C罗", "Ronaldo": "C罗",
    "Lionel Messi": "梅西",
    "Luis Suarez": "苏亚雷斯",
    "Sergio Ramos": "拉莫斯",
    "Karim Benzema": "本泽马",
    "Benzema": "本泽马",
    "Ansu Fati": "法蒂", "Fati": "法蒂",

    # ===== 常见转会目标补充 =====
    "Joao Gomes": "若昂·戈麦斯",
    "Nico Williams": "尼科·威廉姆斯", "Zubimendi": "祖比门迪",
    "Martin Zubimendi": "祖比门迪", "Viktor Gyokeres": "哲凯赖什",
    "Gyokeres": "哲凯赖什",
    "Jonathan David": "乔纳森·戴维", "Santiago Gimenez": "希门尼斯",
    "Gimenez": "希门尼斯",
    "Xavi Simons": "哈维·西蒙斯", "Simons": "西蒙斯",
    "Jeremy Monga": "杰里米·蒙加", "Monga": "蒙加",
}
